/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calcualtorscientific;

/**
 *
 * @author Windows 10
 */
public class CalculatorScientific extends javax.swing.JFrame {

    private String angka = " ";
    double jumlah,angka1,angka2;
    int pilih;

    /**
     * Creates new form CalculatorScientific
     */
    public CalculatorScientific() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PapanArea = new javax.swing.JTextField();
        Bersih = new javax.swing.JButton();
        Angka7 = new javax.swing.JButton();
        Angka8 = new javax.swing.JButton();
        Angka9 = new javax.swing.JButton();
        Angka4 = new javax.swing.JButton();
        Angka5 = new javax.swing.JButton();
        Angka6 = new javax.swing.JButton();
        Angka1 = new javax.swing.JButton();
        Angka2 = new javax.swing.JButton();
        Angka3 = new javax.swing.JButton();
        Angka0 = new javax.swing.JButton();
        koma = new javax.swing.JButton();
        penjumlah = new javax.swing.JButton();
        pengurangan = new javax.swing.JButton();
        perkalian = new javax.swing.JButton();
        pembagian = new javax.swing.JButton();
        Hasil = new javax.swing.JButton();
        Pangkat = new javax.swing.JButton();
        persen = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        log = new javax.swing.JButton();
        Perpangkatan = new javax.swing.JButton();
        akar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Square721 Cn BT", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kalkulator");

        PapanArea.setEditable(false);
        PapanArea.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Bersih.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        Bersih.setText("CLR");
        Bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BersihActionPerformed(evt);
            }
        });

        Angka7.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        Angka7.setText("7");
        Angka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka7ActionPerformed(evt);
            }
        });

        Angka8.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        Angka8.setText("8");
        Angka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka8ActionPerformed(evt);
            }
        });

        Angka9.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        Angka9.setText("9");
        Angka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka9ActionPerformed(evt);
            }
        });

        Angka4.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        Angka4.setText("4");
        Angka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka4ActionPerformed(evt);
            }
        });

        Angka5.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        Angka5.setText("5");
        Angka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka5ActionPerformed(evt);
            }
        });

        Angka6.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        Angka6.setText("6");
        Angka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka6ActionPerformed(evt);
            }
        });

        Angka1.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        Angka1.setText("1");
        Angka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka1ActionPerformed(evt);
            }
        });

        Angka2.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        Angka2.setText("2");
        Angka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka2ActionPerformed(evt);
            }
        });

        Angka3.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        Angka3.setText("3");
        Angka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka3ActionPerformed(evt);
            }
        });

        Angka0.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        Angka0.setText("0");
        Angka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Angka0ActionPerformed(evt);
            }
        });

        koma.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        koma.setText(".");
        koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaActionPerformed(evt);
            }
        });

        penjumlah.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        penjumlah.setText("+");
        penjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjumlahActionPerformed(evt);
            }
        });

        pengurangan.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        pengurangan.setText("-");
        pengurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penguranganActionPerformed(evt);
            }
        });

        perkalian.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        perkalian.setText("*");
        perkalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perkalianActionPerformed(evt);
            }
        });

        pembagian.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        pembagian.setText("/");
        pembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembagianActionPerformed(evt);
            }
        });

        Hasil.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        Hasil.setText("=");
        Hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilActionPerformed(evt);
            }
        });

        Pangkat.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        Pangkat.setText("X²");
        Pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PangkatActionPerformed(evt);
            }
        });

        persen.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        persen.setText("%");
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });

        sin.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        sin.setText("sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });

        cos.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        cos.setText("cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });

        tan.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        tan.setText("tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });

        log.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        log.setText("log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        Perpangkatan.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        Perpangkatan.setText("x^y");
        Perpangkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerpangkatanActionPerformed(evt);
            }
        });

        akar.setFont(new java.awt.Font("Square721 Cn BT", 0, 18)); // NOI18N
        akar.setText("√");
        akar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PapanArea)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cos, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Bersih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Angka1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(Angka4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(koma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Angka7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Angka2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                        .addComponent(Angka5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Angka8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Angka0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(akar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Pangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(persen, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                        .addComponent(Angka9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Angka6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Angka3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Perpangkatan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pembagian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(perkalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pengurangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(penjumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PapanArea, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(persen)
                    .addComponent(Pangkat)
                    .addComponent(Bersih)
                    .addComponent(akar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Angka7)
                    .addComponent(Angka8)
                    .addComponent(Angka9)
                    .addComponent(penjumlah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Angka4)
                    .addComponent(Angka5)
                    .addComponent(Angka6)
                    .addComponent(pengurangan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Angka1)
                    .addComponent(Angka2)
                    .addComponent(Angka3)
                    .addComponent(perkalian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Angka0)
                    .addComponent(pembagian)
                    .addComponent(koma)
                    .addComponent(Perpangkatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sin)
                    .addComponent(cos)
                    .addComponent(tan)
                    .addComponent(log))
                .addGap(18, 18, 18)
                .addComponent(Hasil)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(322, 463));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Angka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka1ActionPerformed
        // TODO add your handling code here: 
        String Angka;
        
        angka += "1";
        PapanArea.setText(angka);

    }//GEN-LAST:event_Angka1ActionPerformed

    private void Angka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka2ActionPerformed
        // TODO add your handling code here:
        String Angka;
        
        angka += "2";
        PapanArea.setText(angka);

    }//GEN-LAST:event_Angka2ActionPerformed

    private void Angka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka3ActionPerformed
        // TODO add your handling code here:
        String Angka;
        
        angka += "3";
        PapanArea.setText(angka);

    }//GEN-LAST:event_Angka3ActionPerformed

    private void Angka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka4ActionPerformed
        // TODO add your handling code here:
        String Angka;
        
        angka += "4";
        PapanArea.setText(angka);

    }//GEN-LAST:event_Angka4ActionPerformed

    private void Angka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka5ActionPerformed
        // TODO add your handling code here:
        String Angka;
        
        angka += "5";
        PapanArea.setText(angka);

    }//GEN-LAST:event_Angka5ActionPerformed

    private void Angka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka6ActionPerformed
        // TODO add your handling code here:
        String Angka;
        
        angka += "6";
        PapanArea.setText(angka);

    }//GEN-LAST:event_Angka6ActionPerformed

    private void Angka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka7ActionPerformed
        // TODO add your handling code here:
        String Angka;
        
        angka += "7";
        PapanArea.setText(angka);

    }//GEN-LAST:event_Angka7ActionPerformed

    private void Angka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka8ActionPerformed
        // TODO add your handling code here:
        String Angka;
        
        angka += "8";
        PapanArea.setText(angka);

    }//GEN-LAST:event_Angka8ActionPerformed

    private void Angka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka9ActionPerformed
        // TODO add your handling code here:
        String Angka;
        
        angka += "9";
        PapanArea.setText(angka);

    }//GEN-LAST:event_Angka9ActionPerformed

    private void Angka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Angka0ActionPerformed
        // TODO add your handling code here:
        
        String Angka;
        
        angka += "0";
        PapanArea.setText(angka);

    }//GEN-LAST:event_Angka0ActionPerformed

    private void BersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BersihActionPerformed
        // TODO add your handling code here:
        PapanArea.setText("");
        angka1 = 0.0;
        angka2 = 0.0;
        jumlah = 0.0;
        angka = "";
    }//GEN-LAST:event_BersihActionPerformed

    private void penjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjumlahActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        PapanArea.setText("+");
        angka = "";
        pilih = 1;

    }//GEN-LAST:event_penjumlahActionPerformed

    private void penguranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penguranganActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        PapanArea.setText("-");
        angka = "";
        pilih = 2;
    }//GEN-LAST:event_penguranganActionPerformed

    private void HasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilActionPerformed
        // TODO add your handling code here:
         switch(pilih){
    case 1:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 + angka2;
            angka = Double.toString(jumlah);
            PapanArea.setText(angka);
            break;
    case 2:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 - angka2;
            angka = Double.toString(jumlah);
            PapanArea.setText(angka);
            break;
    case 3:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 * angka2;
            angka = Double.toString(jumlah);
            PapanArea.setText(angka);
            break;
    case 4:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 / angka2;
            angka = Double.toString(jumlah);
            PapanArea.setText(angka);
            break;
    case 5:           
            jumlah = Math.pow(angka1, 2);
            angka = Double.toString(jumlah);
            PapanArea.setText(angka);
            break;
    case 6:
            jumlah = angka1/100;
            angka = Double.toString(jumlah);
            PapanArea.setText(angka); 
            break;
    case 7:
            jumlah = Math.sin(angka1);
            angka = Double.toString(jumlah);
            PapanArea.setText(angka); 
            break;
    case 8:
            jumlah = Math.cos(angka1);
            angka = Double.toString(jumlah);
            PapanArea.setText(angka); 
            break;
                          
    case 9: 
            jumlah = Math.tan(angka1);
            angka = Double.toString(jumlah);
            PapanArea.setText(angka); 
            break;
    case 10:
            angka2 = Double.parseDouble(angka);
            jumlah = Math.log(angka1);
            angka = Double.toString(jumlah);
            PapanArea.setText(angka);
            break;
    case 11:
            angka2 = Double.parseDouble(angka);
            jumlah = Math.pow(angka1, angka2);
            angka = Double.toString(jumlah);
            PapanArea.setText(angka);  
            break;
    case 12: 
            jumlah = Math.sqrt(angka1);
            angka = Double.toString(jumlah);
            PapanArea.setText(angka);
            break;
   
                
        }
    }//GEN-LAST:event_HasilActionPerformed

    private void perkalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perkalianActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        PapanArea.setText("*");
        angka = "";
        pilih = 3;
    }//GEN-LAST:event_perkalianActionPerformed

    private void pembagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembagianActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        PapanArea.setText("/");
        angka = "";
        pilih = 4;
    }//GEN-LAST:event_pembagianActionPerformed

    private void PangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PangkatActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        PapanArea.setText("^");
        angka = "";
        pilih = 5;
    }//GEN-LAST:event_PangkatActionPerformed

    private void komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaActionPerformed
        // TODO add your handling code here:
        angka += ".";
        PapanArea.setText(angka);
    }//GEN-LAST:event_komaActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        PapanArea.setText("%");
        angka = "";
        pilih = 6;
    }//GEN-LAST:event_persenActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        PapanArea.setText(" Sin ");
        angka = "";
        pilih = 7;
    }//GEN-LAST:event_sinActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        PapanArea.setText(" Tan ");
        angka = "";
        pilih = 8;
    }//GEN-LAST:event_tanActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        PapanArea.setText(" Cos ");
        angka = "";
        pilih = 9;
    }//GEN-LAST:event_cosActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        PapanArea.setText(" Log ");
        angka = "";
        pilih = 10; 
    }//GEN-LAST:event_logActionPerformed

    private void PerpangkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerpangkatanActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        PapanArea.setText("^");
        angka = "";
        pilih = 11;       
    }//GEN-LAST:event_PerpangkatanActionPerformed

    private void akarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akarActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        PapanArea.setText("√");
        angka = "";
        pilih = 12;
    }//GEN-LAST:event_akarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorScientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorScientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorScientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorScientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorScientific().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Angka0;
    private javax.swing.JButton Angka1;
    private javax.swing.JButton Angka2;
    private javax.swing.JButton Angka3;
    private javax.swing.JButton Angka4;
    private javax.swing.JButton Angka5;
    private javax.swing.JButton Angka6;
    private javax.swing.JButton Angka7;
    private javax.swing.JButton Angka8;
    private javax.swing.JButton Angka9;
    private javax.swing.JButton Bersih;
    private javax.swing.JButton Hasil;
    private javax.swing.JButton Pangkat;
    private javax.swing.JTextField PapanArea;
    private javax.swing.JButton Perpangkatan;
    private javax.swing.JButton akar;
    private javax.swing.JButton cos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton koma;
    private javax.swing.JButton log;
    private javax.swing.JButton pembagian;
    private javax.swing.JButton pengurangan;
    private javax.swing.JButton penjumlah;
    private javax.swing.JButton perkalian;
    private javax.swing.JButton persen;
    private javax.swing.JButton sin;
    private javax.swing.JButton tan;
    // End of variables declaration//GEN-END:variables
}
